# Generated by Django 5.2.1 on 2025-05-26 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Área de Saber')),
            ],
            options={
                'verbose_name': 'Área do saber',
                'verbose_name_plural': 'Áreas do saber',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de avaliação')),
            ],
            options={
                'verbose_name': 'Avaliação Tipo',
                'verbose_name_plural': 'Avaliações Tipos',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da ocupação')),
            ],
            options={
                'verbose_name': 'Ocupação',
                'verbose_name_plural': 'Ocupações',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da turma')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do turno')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do curso')),
                ('carga_horaria_total', models.CharField(max_length=100, verbose_name='Carga Horária Total do curso')),
                ('duracao_meses', models.CharField(max_length=100, verbose_name='Duração (em meses) do curso')),
                ('areasaber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areasaber', verbose_name='Área de saber do curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição da avaliação')),
                ('avaliacaotipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.avaliacaotipo', verbose_name='Tipo de avaliação')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso da avaliação')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da disciplina')),
                ('areasaber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areasaber', verbose_name='Área de saber da disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='InstituicaoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da instituição de ensino')),
                ('site', models.CharField(max_length=100, verbose_name='Site da instituição de ensino')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone da instituição de ensino')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade da instituição de ensino')),
            ],
            options={
                'verbose_name': 'Instituição de Ensino',
                'verbose_name_plural': 'Instituições de ensino',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instituicaoensino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino', verbose_name='Instituição de ensino do curso'),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da pessoa')),
                ('pai', models.CharField(max_length=100, verbose_name='Nome do pai da pessoa')),
                ('mae', models.CharField(max_length=100, verbose_name='Nome da mãe da pessoa')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF da pessoa')),
                ('data_nasc', models.CharField(max_length=100, verbose_name='Data de nascimento da pessoa')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail da pessoa')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade da pessoa')),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao', verbose_name='Ocupação da pessoa')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição da ocorrência')),
                ('data', models.CharField(max_length=100, verbose_name='Data da ocorrência')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso onde ocorreu')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina onde ocorreu')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa por trás da ocorrência')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.CharField(max_length=100, verbose_name='Data de início da matrícula')),
                ('data_previsao_termino', models.CharField(max_length=100, verbose_name='Data prevista para o fim da matrícula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso da matrícula')),
                ('instituicaoensino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino', verbose_name='Instituição de ensino da matrícula')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa na matrícula')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_faltas', models.CharField(max_length=100, verbose_name='Número de faltas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Frequência no curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Frequência na disciplina')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Frequência da pessoa')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
            },
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargahoraria', models.CharField(max_length=100, verbose_name='Carga Horária do curso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso das disciplinas')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplinas do curso')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turno', verbose_name='Turno das disciplinas')),
            ],
            options={
                'verbose_name': 'Curso Disciplina',
                'verbose_name_plural': 'Cursos Disciplinas',
            },
        ),
    ]
